INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_1",0,1,4,11,"Looking for a sherpa","eng",1475632990);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_2",0,1,1,1,"","eng",1475632971);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_3",0,3,3,7,"","eng",1475633030);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_4",0,2,4,8,"Sherpa looking to help others","jpn",1475633041);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_5",1,3,3,5,"","eng",1475633165);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_6",1,2,2,4,"","eng",1475633126);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_7",1,3,4,9,"","eng",1475633072);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_8",0,1,1,1,"Sherpa looking to help others","jpn",1475632991);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_9",1,1,1,1,"","eng",1475633009);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_10",0,2,2,4,"Newbs and vets welcome!","eng",1475633158);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_11",0,2,4,8,"","eng",1475633208);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_12",1,3,3,7,"","eng",1475633074);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_13",0,2,2,4,"","spa",1475633054);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_14",1,3,3,5,"Next 2 hours only","eng",1475633162);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_15",1,1,1,2,"","eng",1475632920);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_16",1,3,3,7,"Newbs and vets welcome!","spa",1475632908);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_17",1,2,2,4,"Sherpa looking to help others","ger",1475633218);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_18",0,1,1,1,"","eng",1475633215);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_19",0,3,3,6,"","eng",1475633068);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_20",0,3,4,13,"I really need help!","eng",1475633201);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_21",0,2,2,4,"Sherpa looking to help others","eng",1475633174);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_22",0,2,2,4,"All night run, please be committed!","eng",1475633098);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_23",1,3,3,7,"","jpn",1475633135);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_24",0,1,4,9,"","eng",1475633147);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_25",1,1,1,2,"","eng",1475632957);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_26",1,1,1,2,"I need high-level players","eng",1475633014);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_27",1,1,1,1,"No mic = kick!","jpn",1475633081);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_28",1,3,3,6,"","eng",1475632974);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_29",0,1,1,1,"","eng",1475633127);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_30",0,2,4,12,"","eng",1475633129);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_31",1,3,3,7,"Only between 1 and 4 PM PST please","eng",1475633136);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_32",1,1,1,2,"No mic = kick!","ger",1475633086);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_33",1,2,2,4,"","eng",1475633046);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_34",1,3,3,7,"","eng",1475633128);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_35",0,2,2,4,"","ger",1475633170);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_36",0,3,3,6,"If I miss you try again at 15:00","eng",1475633181);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_37",0,1,1,3,"Need 1 more","jpn",1475632923);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_38",0,1,4,11,"","jpn",1475633008);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_39",1,1,1,3,"Newbs and vets welcome!","spa",1475632968);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_40",1,1,4,10,"I will run this again at 4pm if I miss you","ger",1475633079);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_41",1,3,4,13,"Looking for 4","jpn",1475632941);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_42",1,2,2,4,"","eng",1475633216);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_43",1,1,1,2,"","eng",1475633089);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_44",1,1,1,2,"If I miss you try again at 15:00","eng",1475633001);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_45",0,2,4,12,"","jpn",1475632933);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_46",0,2,2,4,"Please message me before sending friend request","eng",1475633048);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_47",0,2,2,4,"","eng",1475633187);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_48",1,3,3,5,"","eng",1475633087);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_49",0,2,2,4,"","eng",1475632950);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_50",1,2,2,4,"","eng",1475633094);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_51",0,2,2,4,"Looking for 4","jpn",1475633178);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_52",0,3,4,13,"Next 2 hours only","ger",1475632925);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_53",0,3,4,10,"Newbs and vets welcome!","eng",1475633075);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_54",0,2,2,4,"I'm very skilled","eng",1475633221);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_55",0,2,2,4,"I'm very skilled","jpn",1475633100);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_56",0,1,4,10,"","jpn",1475632928);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_57",0,2,4,8,"","jpn",1475633124);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_58",1,1,1,3,"","eng",1475633153);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_59",1,3,4,10,"I'm very skilled","ger",1475632932);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_60",0,3,3,6,"","eng",1475632962);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_61",0,2,2,4,"","eng",1475633011);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_62",1,1,1,2,"","eng",1475632953);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_63",0,1,1,3,"Need 1 more","ger",1475632930);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_64",1,2,2,4,"No mic = kick!","jpn",1475632997);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_65",1,2,2,4,"","eng",1475633171);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_66",1,3,3,5,"","eng",1475632979);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_67",1,2,2,4,"All night run, please be committed!","eng",1475633120);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_68",1,1,4,9,"Newbs and vets welcome!","eng",1475633040);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_69",0,2,2,4,"Looking for 4","eng",1475632947);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_70",1,2,2,4,"","eng",1475633038);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_71",1,3,3,7,"I will run this again at 4pm if I miss you","eng",1475632977);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_72",1,3,3,7,"","eng",1475632942);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_73",1,2,4,8,"","eng",1475633223);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_74",1,1,4,11,"Only need 3 more!","eng",1475633003);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_75",1,2,2,4,"Will do other modes as well","eng",1475633034);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_76",1,3,3,5,"","eng",1475632907);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_77",0,3,3,6,"","eng",1475632958);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_78",0,3,3,5,"","eng",1475633082);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_79",1,1,1,2,"No laggy players PLEASE!","eng",1475633096);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_80",0,1,1,1,"I'm very skilled","eng",1475633058);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_81",1,1,1,2,"","spa",1475633164);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_82",0,1,1,2,"","eng",1475633105);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_83",0,2,4,8,"No mic = kick!","eng",1475633107);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_84",1,1,1,1,"I'm very skilled","eng",1475633023);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_85",1,3,3,6,"Need 1 more","eng",1475633106);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_86",0,1,4,9,"No mic = kick!","spa",1475633029);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_87",1,3,3,7,"","eng",1475633166);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_88",1,3,3,5,"","ger",1475633156);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_89",0,1,1,3,"I'm very skilled","eng",1475633224);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_90",0,3,3,5,"Will do other modes as well","eng",1475632954);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_91",1,1,1,3,"No mic = kick!","eng",1475633179);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_92",1,2,2,4,"Need 1 more","jpn",1475633077);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_93",0,1,1,3,"","eng",1475633025);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_94",0,3,3,5,"All night run, please be committed!","eng",1475632918);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_95",0,2,4,12,"","eng",1475633194);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_96",1,1,4,8,"If I miss you try again at 15:00","ger",1475633154);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_97",0,1,4,10,"Looking for 4","eng",1475632969);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_98",0,2,4,12,"","eng",1475632946);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_99",0,2,4,8,"No laggy players PLEASE!","eng",1475633205);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_100",1,1,4,8,"","ger",1475633145);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_101",1,1,1,3,"If I miss you try again at 15:00","eng",1475632913);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_102",0,1,1,1,"","eng",1475633209);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_103",1,1,4,8,"","eng",1475633167);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_104",0,3,3,7,"","eng",1475632978);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_105",1,3,3,7,"I'm very skilled","spa",1475633024);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_106",1,1,4,8,"Top player looking to help","eng",1475633028);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_107",1,1,1,3,"","eng",1475632960);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_108",1,3,4,13,"I'm very skilled","eng",1475633099);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_109",1,1,4,11,"I will run this again at 4pm if I miss you","spa",1475633080);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_110",0,3,3,6,"Next 2 hours only","jpn",1475633037);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_111",0,3,3,5,"","eng",1475633202);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_112",0,3,3,7,"","jpn",1475633102);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_113",0,2,4,10,"I really need help!","eng",1475633161);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_114",1,3,3,5,"Will do other modes as well","eng",1475632976);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_115",1,3,3,6,"","eng",1475633026);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_116",0,1,4,8,"","eng",1475633152);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_117",1,1,1,2,"","eng",1475632981);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_118",0,3,3,5,"","eng",1475633210);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_119",1,1,1,2,"Newbs and vets welcome!","eng",1475632949);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_120",1,2,2,4,"","eng",1475633112);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_121",0,2,2,4,"Top player looking to help","eng",1475633103);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_122",0,3,3,7,"","eng",1475633115);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_123",0,2,4,9,"","eng",1475633188);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_124",1,3,4,10,"","eng",1475632909);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_125",1,1,4,8,"No mic = kick!","eng",1475633220);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_126",0,2,2,4,"Looking for a sherpa","jpn",1475633184);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_127",0,2,4,8,"","eng",1475633190);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_128",0,2,2,4,"","eng",1475632985);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_129",0,3,3,5,"","eng",1475633104);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_130",1,1,1,3,"","jpn",1475633043);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_131",1,3,3,5,"No mic = kick!","jpn",1475633159);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_132",1,2,2,4,"Looking for 4","eng",1475633045);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_133",1,1,1,2,"If I miss you try again at 15:00","eng",1475633130);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_134",1,1,1,3,"No laggy players PLEASE!","eng",1475632906);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_135",0,2,2,4,"I'm very skilled","eng",1475632948);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_136",0,2,2,4,"Need 1 more","eng",1475633036);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_137",0,2,2,4,"","ger",1475632938);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_138",0,3,3,7,"Mic and clean language or kick!","eng",1475633070);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_139",0,3,4,13,"Newbs and vets welcome!","jpn",1475633180);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_140",1,1,1,2,"","eng",1475633031);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_141",0,3,4,8,"Top player looking to help","eng",1475632921);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_142",0,3,3,7,"Only need 3 more!","eng",1475632989);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_143",0,3,4,9,"Please message me before sending friend request","eng",1475633219);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_144",1,3,4,10,"","eng",1475633084);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_145",1,1,4,9,"I will run this again at 4pm if I miss you","jpn",1475633010);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_146",1,1,1,1,"","eng",1475633143);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_147",0,2,4,9,"","eng",1475633097);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_148",0,1,1,2,"","jpn",1475633163);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_149",1,1,1,3,"","eng",1475632905);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_150",1,2,2,4,"Need 1 more","eng",1475632910);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_151",0,3,4,9,"Only need 3 more!","eng",1475633060);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_152",0,2,4,9,"","spa",1475633200);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_153",0,2,2,4,"","eng",1475633113);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_154",1,2,2,4,"Please message me before sending friend request","spa",1475633059);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_155",0,3,4,13,"","jpn",1475633122);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_156",0,1,1,1,"","eng",1475633144);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_157",0,2,2,4,"","eng",1475633172);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_158",1,3,3,7,"","eng",1475633101);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_159",0,3,3,7,"Only between 1 and 4 PM PST please","ger",1475633050);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_160",1,1,1,1,"","jpn",1475633175);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_161",0,3,3,5,"Mic and clean language or kick!","eng",1475633000);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_162",1,2,2,4,"","eng",1475633002);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_163",1,1,1,1,"","eng",1475633004);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_164",1,3,3,6,"","eng",1475633211);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_165",0,1,1,3,"Only between 1 and 4 PM PST please","eng",1475633137);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_166",1,1,1,2,"","ger",1475633017);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_167",0,2,2,4,"","jpn",1475633177);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_168",1,2,4,8,"","eng",1475632924);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_169",1,3,3,5,"No laggy players PLEASE!","spa",1475632987);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_170",0,2,2,4,"No mic = kick!","eng",1475633131);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_171",0,3,4,10,"Looking for 4","eng",1475633111);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_172",1,2,2,4,"","eng",1475632919);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_173",1,2,2,4,"Mic required!","jpn",1475633222);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_174",1,1,4,10,"Top player looking to help","eng",1475633150);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_175",1,3,4,9,"Looking for 4","eng",1475633051);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_176",0,1,1,1,"Only between 1 and 4 PM PST please","eng",1475633067);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_177",0,2,4,8,"Doing this between 17:00 and 20:00","spa",1475633151);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_178",0,2,4,9,"","eng",1475633123);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_179",0,2,4,9,"Only between 1 and 4 PM PST please","ger",1475632963);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_180",0,3,3,6,"Doing this between 17:00 and 20:00","ger",1475633073);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_181",0,3,3,7,"Only need 3 more!","eng",1475633108);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_182",1,3,4,9,"","eng",1475633006);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_183",1,1,1,2,"","eng",1475632935);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_184",1,2,2,4,"Mic required!","eng",1475633191);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_185",1,2,2,4,"","eng",1475633012);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_186",0,1,1,1,"","spa",1475633121);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_187",1,1,4,9,"","eng",1475633212);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_188",1,3,3,6,"Mic required!","eng",1475633196);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_189",0,1,1,2,"","eng",1475633078);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_190",0,2,2,4,"","eng",1475632911);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_191",1,2,2,4,"Top player looking to help","eng",1475633053);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_192",1,2,2,4,"","eng",1475633066);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_193",1,1,4,8,"Looking for a sherpa","eng",1475632994);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_194",0,1,1,1,"Newbs and vets welcome!","eng",1475633110);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_195",1,3,3,5,"","eng",1475633148);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_196",0,3,3,7,"","spa",1475633140);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_197",1,2,2,4,"","eng",1475633062);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_198",0,2,2,4,"No mic = kick!","ger",1475633109);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_199",1,2,2,4,"Top player looking to help","eng",1475633016);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_200",1,1,1,3,"","eng",1475632999);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_201",0,3,4,10,"I'm very skilled","ger",1475632912);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_202",1,3,3,6,"Please message me before sending friend request","eng",1475633217);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_203",1,1,1,3,"Please message me before sending friend request","eng",1475633055);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_204",0,2,2,4,"All night run, please be committed!","eng",1475632914);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_205",1,1,4,10,"","eng",1475633146);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_206",1,3,3,7,"Top player looking to help","spa",1475632922);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_207",1,1,1,3,"Will do other modes as well","jpn",1475633005);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_208",0,3,3,7,"No mic = kick!","eng",1475632943);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_209",0,3,3,5,"","eng",1475632915);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_210",0,2,2,4,"","eng",1475632983);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_211",1,1,1,2,"I will run this again at 4pm if I miss you","spa",1475632956);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_212",1,2,2,4,"Need 1 more","eng",1475632929);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_213",1,1,1,2,"","eng",1475632926);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_214",0,2,4,12,"","eng",1475633204);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_215",1,3,3,6,"","eng",1475633133);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_216",1,1,1,1,"Looking for a sherpa","eng",1475633085);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_217",1,3,4,8,"Next 2 hours only","eng",1475632970);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_218",1,3,4,10,"","eng",1475633117);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_219",1,1,1,1,"No mic = kick!","spa",1475632967);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_220",1,1,1,3,"","eng",1475633169);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_221",1,3,3,7,"Looking for 4","eng",1475633091);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_222",0,3,3,5,"Looking for 4","jpn",1475632952);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_223",1,3,3,6,"Looking for 4","ger",1475633063);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_224",0,2,2,4,"Will do other modes as well","eng",1475632917);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_225",0,1,1,3,"Doing this between 17:00 and 20:00","eng",1475633119);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_226",0,2,2,4,"","eng",1475633088);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_227",0,3,3,6,"","eng",1475633049);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_228",0,2,2,4,"","eng",1475633065);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_229",0,3,3,7,"","eng",1475633185);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_230",1,1,1,3,"","spa",1475633195);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_231",0,3,3,5,"","eng",1475633213);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_232",1,3,4,13,"Only need 3 more!","ger",1475633183);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_233",0,3,3,6,"If I miss you try again at 15:00","jpn",1475633118);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_234",1,2,2,4,"","eng",1475632984);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_235",1,3,3,5,"Only need 3 more!","eng",1475633176);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_236",0,1,4,9,"","spa",1475633020);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_237",1,1,1,2,"Looking for 4","eng",1475632951);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_238",1,3,4,8,"","eng",1475633018);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_239",0,2,2,4,"No laggy players PLEASE!","eng",1475633007);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_240",0,2,2,4,"","ger",1475632927);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_241",1,1,1,2,"","eng",1475633206);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_242",0,3,3,5,"Looking for a sherpa","eng",1475633193);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_243",1,1,1,3,"Doing this between 17:00 and 20:00","ger",1475633056);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_244",1,2,2,4,"","eng",1475633092);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_245",1,3,3,7,"I really need help!","eng",1475633157);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_246",0,1,4,8,"Looking for 4","eng",1475633139);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_247",1,3,3,5,"","spa",1475632966);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_248",1,3,3,5,"No laggy players PLEASE!","jpn",1475632945);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_249",1,2,2,4,"I'm very skilled","eng",1475632961);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_250",1,1,1,1,"","eng",1475633173);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_251",0,1,4,10,"Looking for 4","eng",1475632959);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_252",1,3,4,13,"I need high-level players","spa",1475633044);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_253",0,3,3,7,"","eng",1475633189);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_254",1,1,4,9,"Sherpa looking to help others","eng",1475632996);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_255",0,2,2,4,"","eng",1475632937);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_256",1,1,1,3,"Only between 1 and 4 PM PST please","eng",1475633199);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_257",1,2,2,4,"","spa",1475633125);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_258",0,1,1,3,"","eng",1475633116);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_259",0,1,1,1,"Only between 1 and 4 PM PST please","eng",1475633203);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_260",0,2,2,4,"I need high-level players","spa",1475633019);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_261",1,2,2,4,"Top player looking to help","eng",1475632931);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_262",0,1,1,2,"Need 1 more","eng",1475633134);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_263",0,2,2,4,"Only need 3 more!","eng",1475633093);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_264",1,3,3,7,"","eng",1475633214);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_265",1,2,2,4,"Looking for 4","eng",1475633090);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_266",0,2,4,12,"","eng",1475633061);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_267",0,1,1,3,"No mic = kick!","eng",1475633021);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_268",1,3,3,5,"","eng",1475633076);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_269",1,1,1,3,"Mic required!","ger",1475633015);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_270",1,2,2,4,"No laggy players PLEASE!","jpn",1475632992);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_271",1,1,4,10,"","eng",1475633197);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_272",1,3,3,7,"","eng",1475633064);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_273",0,1,1,1,"Will do other modes as well","eng",1475632995);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_274",1,2,4,12,"Need 1 more","spa",1475633022);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_275",0,2,2,4,"","spa",1475632955);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_276",1,1,4,10,"","eng",1475633142);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_277",1,1,1,3,"I will run this again at 4pm if I miss you","eng",1475632964);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_278",0,3,3,5,"No laggy players PLEASE!","eng",1475633141);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_279",0,3,3,5,"","jpn",1475633114);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_280",1,1,1,2,"","eng",1475632980);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_281",0,1,1,3,"Top player looking to help","eng",1475633071);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_282",1,3,3,5,"No laggy players PLEASE!","eng",1475633095);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_283",0,2,2,4,"","eng",1475632965);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_284",0,1,1,3,"No laggy players PLEASE!","eng",1475633052);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_285",0,2,4,9,"","eng",1475633207);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_286",0,2,2,4,"Next 2 hours only","eng",1475632973);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_287",1,1,1,1,"I need high-level players","eng",1475633057);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_288",0,3,3,5,"Mic and clean language or kick!","eng",1475633168);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_289",1,2,2,4,"","eng",1475633047);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_290",0,3,3,7,"","jpn",1475633032);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_291",0,2,4,10,"","eng",1475633039);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_292",1,1,4,10,"Mic and clean language or kick!","eng",1475633069);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_293",1,3,4,10,"","eng",1475633132);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_294",0,3,3,5,"","eng",1475632988);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_295",0,3,3,6,"","eng",1475633042);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_296",1,2,2,4,"","eng",1475632916);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_297",1,2,2,4,"","ger",1475633192);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_298",1,3,3,7,"","eng",1475633013);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_299",1,2,2,4,"I will run this again at 4pm if I miss you","eng",1475633083);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_300",0,1,1,3,"Top player looking to help","eng",1475633186);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_301",0,2,2,4,"","eng",1475632940);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_302",0,2,4,12,"","eng",1475632975);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_303",1,2,2,4,"Doing this between 17:00 and 20:00","eng",1475633160);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_304",1,3,3,5,"","eng",1475632934);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_305",0,1,1,2,"","eng",1475632986);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_306",0,1,4,9,"I'm very skilled","jpn",1475632982);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_307",1,2,2,4,"Top player looking to help","eng",1475632998);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_308",1,2,2,4,"","eng",1475633149);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_309",0,3,3,5,"","eng",1475633138);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_310",0,2,4,10,"Sherpa looking to help others","eng",1475632939);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_311",0,1,1,2,"","eng",1475633155);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_312",0,3,3,6,"","eng",1475632993);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_313",0,1,1,2,"Doing this between 17:00 and 20:00","spa",1475632944);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_314",0,1,1,1,"","eng",1475633035);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_315",1,2,2,4,"","eng",1475632972);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_316",1,1,1,2,"I'm very skilled","eng",1475633027);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_317",0,1,1,1,"Need 1 more","eng",1475632936);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_318",0,2,2,4,"","eng",1475633182);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_319",0,3,3,5,"Need 1 more","ger",1475633033);
INSERT INTO Groups (group_user, group_iam, group_system, group_game, group_activity, group_details, group_language, group_time) VALUES ("testUser_320",1,1,4,11,"","eng",1475633198);